var rfr = require('rfr'),
mongoose = require('mongoose'),
practiceAreas = mongoose.model('practice_areas');

var practiceAreaModel = rfr('/server/models/static/practiceAreas');

practiceAreas.count().exec(function(err, res) {
  if (res === 0) {
    practiceAreas.insertMany([
      {'name': 'Administrative Law'},
      {'name': 'Admiralty and Maritime Law'},
      {'name': 'Agricultural Law'},
      {'name': 'Alternative Dispute Resolution'},
      {'name': 'Antitrust and Trade Regulation'},
      {'name': 'Appellate Practice'},
      {'name': 'Aviation and Aerospace Law'},
      {'name': 'Banking Law'},
      {'name': 'Bankruptcy Law'},
      {'name': 'Business Law'},
      {'name': 'Civil Rights'},
      {'name': 'Class Actions'},
      {'name': 'Commercial Law'},
      {'name': 'Communications Law'},
      {'name': 'Constitutional Law'},
      {'name': 'Construction Law'},
      {'name': 'Contracts Law'},
      {'name': 'Corporate Law'},
      {'name': 'Criminal Law'},
      {'name': 'Debtor and Creditor'},
      {'name': 'Education Law'},
      {'name': 'Elder Law'},
      {'name': 'Election, Campaign Finance and Political Law'},
      {'name': 'Eminent Domain'},
      {'name': 'Employee Benefits'},
      {'name': 'Energy Law'},
      {'name': 'Entertainment Law'},
      {'name': 'Environmental Law'},
      {'name': 'Family Law'},
      {'name': 'Finance'},
      {'name': 'Franchise Law'},
      {'name': 'Government Affairs'},
      {'name': 'Government Contracts'},
      {'name': 'Health Care Law'},
      {'name': 'Immigration Law'},
      {'name': 'Indians and Native Populations'},
      {'name': 'Insurance Law'},
      {'name': 'Intellectual Property Law'},
      {'name': 'International Law'},
      {'name': 'International Trade'},
      {'name': 'Internet Law'},
      {'name': 'Investment Law'},
      {'name': 'Labor and Employment Law'},
      {'name': 'Legal Malpractice'},
      {'name': 'Licensing'},
      {'name': 'Litigation'},
      {'name': 'Media Law'},
      {'name': 'Medical Malpractice'},
      {'name': 'Mergers and Acquisitions'},
      {'name': 'Military Law'},
      {'name': 'Natural Resources Law'},
      {'name': 'Occupational Safety and Health Law'},
      {'name': 'Oil and Gas Law'},
      {'name': 'Personal Injury Law'},
      {'name': 'Products Liability Law'},
      {'name': 'Professional Liability Law'},
      {'name': 'Real Estate Law'},
      {'name': 'Sports Law'},
      {'name': 'Securities Law'},
      {'name': 'Tax Law'},
      {'name': 'Technology and Science'},
      {'name': 'Toxic Tort Law'},
      {'name': 'Transportation Law'},
      {'name': 'Trusts and Estate Law'},
      {'name': 'Wills and Probate'},
      {'name': 'White Collar Crime'},
      {'name': 'Workers Compensation Law'},
      {'name': 'Zoning, Planning and Land Use Law'}
    ], function(err, res) {
      practiceAreaModel.get();
    });
  } else {
    practiceAreaModel.get();
  }
});
